spring:
  messages:
    basename: static/i18n/messages
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Decathl0n
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 32
        max-idle: 8
        min-idle: 8
        max-wait: -1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.maersk.apawnd.wms.standard.model
server:
  port: 18080

biz:
  event-queue-service:
    config:
      batch-queue-count: 500
      event-type: WS
      retry-count: 3
      timeout-retry-minute: 5
      mail-alert: false
      job-sleep-second: 20
      job-skip-second: 10
