apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-domain-deployment
  labels:
    app: poc-domain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-domain
  template:
    metadata:
      labels:
        app: poc-domain
    spec:
      containers:
        - name: poc-domain
          image: 192.168.99.1:8083/poc-domain
          imagePullPolicy: Always
          ports:
            - containerPort: 18080
          env:
            - name: JAVA_OPTIONS
              value: -Dspring.profiles.active=development