package com.maersk.apawnd.wms.standard.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.ibatis.type.Alias;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

@Data
@NoArgsConstructor
@Alias("ItemMasterModel")
public class ItemMasterModel implements Serializable {

  private Integer itemMasterId;
  private String itemNumber;
  private String description;
  private String uom;
  private String inventoryType;
  private Integer shelfLife;
  private String altItemNumber;
  private String commodityCode;
  private String naftaPrefCriteria;
  private String naftaProducer;
  private String naftaNetCost;
  private BigDecimal price;
  private BigDecimal stdHandQty;
  private String stdQtyUom;
  private String inspectionCode;
  private String serialized;
  private String lotControl;
  private String whId;
  private BigDecimal reorderPoint;
  private BigDecimal reorderQty;
  private String cycleCountClass;
  private Instant lastCountDate;
  private String classId;
  private String pickLocation;
  private String stackingSeq;
  private String commentFlag;
  private String verFlag;
  private String upc;
  private BigDecimal unitWeight;
  private BigDecimal tareWeight;
  private String hazMaterial;
  private String invCat;
  private String invClass;
  private BigDecimal unitVolume;
  private BigDecimal nestedVolume;
  private String xdockProfileId;
  private String pickPutId;
  private String suggestedDisposition;
  private BigDecimal length;
  private BigDecimal width;
  private BigDecimal height;
  private Integer sampleRate;
  private Integer compatibilityId;
  private Integer commodityTypeId;
  private Integer freightClassId;
  private String auditRequired;
  private String ownerId;
  private String msdsUrl;
  private String expirationDateControl;
  private String uccCompanyPrefix;
  private Integer attributeCollectionId;
  private String color;
  private String size;
  private String style;
  private Integer piecePerCtn;
  private String displayItemNumber;
  private String clientCode;
  private String serialScan;
  private String diaControl;
  private String brand;
  private String complyCodes;
  private String productNameUp;
  private String productNameDown;
  private Integer stackLimit;
  private String compatibilityName;
  private String genericField1;
  private String genericField2;
  private String genericField3;
  private String genericField4;
  private String genericField5;
  private String genericField6;
  private String genericField7;
  private String genericField8;
  private String genericField9;
  private String genericField10;
  private String genericField11;
  private String genericField12;
  private String genericField13;
  private String genericField14;
  private String genericField15;
  private String pickBinNumber;
  private String genericField16;
  private String genericField17;
  private String genericField18;
  private String genericField19;
  private String genericField20;
  private BigDecimal lpHandCbm;
  private BigDecimal lpHandCarton;
  private BigDecimal serialNoQty;
  private BigDecimal netWeight;
  private BigDecimal pcsPerLp;
  private String pickBinControl;
  private String createdBy;
  private String updatedBy;
  private Instant createDate;
  private Instant updatedDate;
}
