spring:
  application:
    name: poc-domain
  messages:
    basename: static/i18n/messages
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Decathl0n
logging:
  config: classpath:logback-spring.xml
server:
  port: 18080
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'