spring:
  messages:
    basename: static/i18n/messages
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Decathl0n

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 18080

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'

env: local